/* global console, process */

import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { frontmatterProblems } from './skill-frontmatter.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skillNames = [
  'tadori-spec-guardian',
  'tadori-validation',
  'tadori-indexer',
  'tadori-visual-workflow',
];
const targets = ['.claude/skills', '.agents/skills'];

const problems = [];
for (const name of skillNames) {
  problems.push(...frontmatterProblems(name, await readFile(join(root, 'agent-skills', name, 'SKILL.md'))));
}
if (problems.length > 0) {
  for (const problem of problems) console.error(`Refusing to sync. ${problem}`);
  process.exit(1);
}

for (const target of targets) {
  const targetRoot = join(root, target);
  await mkdir(targetRoot, { recursive: true });

  // Read the previous manifest before overwriting it: only directories it
  // lists were generated by us, so only those may be removed when stale.
  let previouslyGenerated = [];
  try {
    const previous = JSON.parse((await readFile(join(targetRoot, '.tadori-generated.json'), 'utf8')).replace(/^\uFEFF/, ''));
    if (Array.isArray(previous.generatedSkills)) previouslyGenerated = previous.generatedSkills;
  } catch { /* first sync into this target */ }

  for (const name of skillNames) {
    const source = join(root, 'agent-skills', name, 'SKILL.md');
    const destination = join(targetRoot, name, 'SKILL.md');
    const contents = await readFile(source);
    await mkdir(dirname(destination), { recursive: true });
    try {
      if ((await readFile(destination)).equals(contents)) continue;
    } catch { /* copy missing generated file */ }
    await cp(source, destination);
  }

  for (const entry of await readdir(targetRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || !previouslyGenerated.includes(entry.name)) continue;
    if (!skillNames.includes(entry.name)) await rm(join(targetRoot, entry.name), { recursive: true });
  }

  const manifest = `${JSON.stringify({ generatedSkills: skillNames }, null, 2)}\n`;
  await writeFile(join(targetRoot, '.tadori-generated.json'), manifest);
}

console.log(`Synchronized ${skillNames.length} Tadori skills to .claude/skills and .agents/skills.`);
